create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  name text unique not null,
  high_score integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.leaderboard enable row level security;

create policy "Public read leaderboard" on public.leaderboard
  for select using (true);

create policy "Public upsert leaderboard" on public.leaderboard
  for insert with check (true);

create policy "Public update leaderboard" on public.leaderboard
  for update using (true);
